feat(HACBS-2339): add new releasePlan controller
redhat-appstudio/release-service pull request #210
Opened 2023-07-10 09:09 UTC by davidmogar

This controller will set the owner reference for all releasePlans.

2023-07-10 13:30 UTC, theflockers requested changes
Some small changes required - or not.

2023-07-10 13:34 UTC, davidmogar commented on loader/loader_test.go
> +			Expect(returnedObjects).To(HaveLen(1))
All the tests use the same name. The function is returning an object. Then I check that the type matches.

2023-07-10 18:26 UTC, johnbieren requested changes

2023-07-11 08:58 UTC, theflockers approved these changes

2023-07-11 12:29 UTC, merged