fix(RHTAPBUGS-560): ensure each pipelinerun uses its own subdir
redhat-appstudio/release-service pull request #232
Opened 2023-08-07 12:55 UTC by mmalina

When release pipelineruns are created, they will always use the same shared workspace (provided by the default PVC, or one defined in the given ReleaseStrategy). This wasn't an issue before, but now that we started using the workspace to share snapshot and other data from task to task, we found one that two simultaneously running pipelineruns can alter each other's data. We need to prevent that.

This typically happens when you have two or more components in your app and so there are multiple pipeline runs, oftentimes running around the same time.

The solution is to use a subdir when passing the PVC in the PR. The subdir is based on the PR's UID, so it should always be unique.

2023-08-07 18:09 UTC, johnbieren commented
CI passed but there are no `pipelineruns`? Am I looking in the wrong place @kasemAlem? https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_release-service/232/pull-ci-redhat-appstudio-release-service-main-release-service-e2e/1688534323294113792/artifacts/release-service-e2e/redhat-appstudio-gather/artifacts/pipelineruns.json

2023-08-08 08:05 UTC, kasemAlem commented
> CI passed but there are no `pipelineruns`? Am I looking in the wrong place @kasemAlem? https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_release-service/232/pull-ci-redhat-appstudio-release-service-main-release-service-e2e/1688534323294113792/artifacts/release-service-e2e/redhat-appstudio-gather/artifacts/pipelineruns.json

You are right @johnbieren , file is empty and it means there was no failures , 
the files at end of a run should contains CR that failed, and here e2e-tests passed then no CR was added .

2023-08-08 08:47 UTC, mmalina commented
@johnbieren plus the test has been disabled in e2e for now, but not sure exactly when this test run started (I can't see it anymore), so not sure if it was merged yet or not: https://github.com/redhat-appstudio/e2e-tests/pull/685

I will have to create an accompanying PR in e2e to enable it.

2023-08-08 08:50 UTC, mmalina commented
FYI, I tested the subpath and the `$(context.pipelineRun.uid)` expansion locally using Kind + Tekton + a PVC based on a local directory mounted on the Kind node. And I was able to confirm that it works as expected.

2023-08-08 08:56 UTC, kasemAlem approved these changes

2023-08-08 11:37 UTC, davidmogar requested changes

2023-08-08 11:37 UTC, davidmogar commented on tekton/pipeline_run.go
> +		SubPath: releaseName + "-$(context.pipelineRun.uid)",
This line is not tested.

2023-08-08 11:38 UTC, davidmogar commented on tekton/pipeline_run.go
> +		SubPath: releaseName + "-$(context.pipelineRun.uid)",
Forget, I'm blind.

2023-08-08 11:38 UTC, davidmogar approved these changes

2023-08-09 06:51 UTC, mmalina commented
The [e2e test run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_release-service/232/pull-ci-redhat-appstudio-release-service-main-release-service-e2e/1688876644623716352) failed.

But it actually failed on the other issue that we're facing - the one that needs to be fixed in Pyxis. Here's the [pod log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_release-service/232/pull-ci-redhat-appstudio-release-service-main-release-service-e2e/1688876644623716352/artifacts/release-service-e2e/gather-extra/artifacts/pods/release-e2e-pyxis-managed-zois_release-pipelinerun-xhsmc-push-sbom-to-pyxis-pod_step-push-sbom-files-to-pyxis.log):

```
Uploading sbom to Pyxis: 64d231910005e06353e6cc2d.json
2023-08-08 12:14:33,456 [upload_sbom] INFO Content manifest ID: 64d231a9235f835dc5609c62
2023-08-08 12:14:33,460 [upload_sbom] INFO Loaded 113 components from sbom file.
2023-08-08 12:14:33,460 [upload_sbom] INFO Processing component 1/113
2023-08-08 12:14:33,607 [pyxis] ERROR Pyxis GraphQL query 'create_content_manifest_component_for_manifest' failed: Marshmallow error: {'licenses': {0: {'license': {'id': ['Missing data for required field.']}}}}
2023-08-08 12:14:33,607 [pyxis] ERROR Pyxis trace_id: 0xdc116772b86e51596fe929eb73d1a607
Traceback (most recent call last):
  File "/home/pyxis/upload_sbom", line 347, in <module>
    main()
  File "/home/pyxis/upload_sbom", line 343, in main
    upload_sbom(args.pyxis_graphql_api, image_id, args.sbom_path)
  File "/home/pyxis/upload_sbom", line 141, in upload_sbom
    component_id = create_content_manifest_component(
  File "/home/pyxis/upload_sbom", line 243, in create_content_manifest_component
    data = pyxis.graphql_query(
  File "/home/pyxis/pyxis.py", line 108, in graphql_query
    raise RuntimeError(error_msg)
RuntimeError: Pyxis GraphQL query 'create_content_manifest_component_for_manifest' failed: Marshmallow error: {'licenses': {0: {'license': {'id': ['Missing data for required field.']}}}}
```

This happens one step further - at it least it didn't fail on mismatching number of imageIDs and imageURLs as before. And this failure gives us an opportunity to explore the gathered artifacts to verify if this PR's change works as expected. So let's see.

If we look at the [pipelineruns](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_release-service/232/pull-ci-redhat-appstudio-release-service-main-release-service-e2e/1688876644623716352/artifacts/release-service-e2e/redhat-appstudio-gather/artifacts/pipelineruns.json) and search for `"subpath"`, we can find two occurrences in the two release PRs:
```
"subPath": "appstudio-tgbrl-x78q7-$(context.pipelineRun.uid)"
...
"subPath": "appstudio-jc5w8-2vtnz-$(context.pipelineRun.uid)"
```

That's good. Now if we look at the [taskruns](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_release-service/232/pull-ci-redhat-appstudio-release-service-main-release-service-e2e/1688876644623716352/artifacts/release-service-e2e/redhat-appstudio-gather/artifacts/taskruns.json) and once again search for `"subpath"`, you can see that here the tekton context variable is expanded as expected. There are 12 occurrences in total, 6 for each PR:

```
"subPath": "appstudio-tgbrl-x78q7-d156663f-7c84-4e95-90bb-31f048c6c05a"
...
"subPath": "appstudio-jc5w8-2vtnz-81e9aee2-c7eb-4f1f-b860-48f7ba2cdcf2"
```

So this confirms that this fix works as expected, but we were not able to get a passing e2e run due to that Pyxis issue ([CLOUDWF-9388](https://issues.redhat.com/browse/CLOUDWF-9388)). The Pyxis team said they would fix it today (Wed), so it's probably best for us to wait for that fix.

2023-08-09 12:21 UTC, johnbieren approved these changes
Seems to work based on your investigation of the CI failure

2023-08-14 13:00 UTC, davidmogar commented
Agreed with Martin on merging this one as the E2E failure is not related to this change.

2023-08-14 13:00 UTC, merged