chore: remove .idea directory
redhat-appstudio/release-service pull request #276
Opened 2023-10-12 14:03 UTC by johnbieren

No reason to have config files for a specific IDE in our repo.

2023-10-12 14:06 UTC, scoheb submitted a review, later dismissed

2023-10-12 14:28 UTC, kasemAlem submitted a review, later dismissed

2023-10-12 14:48 UTC, davidmogar requested changes
Change the .gitignore as well. Replace all the IDEA stuff with `.idea`.

2023-10-12 19:02 UTC, johnbieren commented
> Change the .gitignore as well. Replace all the IDEA stuff with `.idea`.

done

2023-10-19 15:47 UTC, johnbieren commented
/retest-required

2023-10-19 20:39 UTC, scoheb approved these changes

2023-10-19 20:39 UTC, happybhati approved these changes

2023-10-19 20:40 UTC, merged