feat(RHTAPREL-711): add shortnames to CRDs
redhat-appstudio/release-service pull request #299
Opened 2023-11-13 16:29 UTC by johnbieren

Add the rp shortname for ReleasePlan and rpa shortname for ReleasePlanAdmission.

```
$ oc get rp
NAME   APPLICATION   TARGET
rp     foo           rpas

$ oc get rpa
NAME   ENVIRONMENT   ORIGIN
rpa    production    rpas
```

2023-11-13 16:53 UTC, happybhati approved these changes

2023-11-13 18:48 UTC, mmalina submitted a review, later dismissed
Nice!

2023-11-14 10:33 UTC, davidmogar requested changes
This has been in my bucket list for a long time. Thanks for creating the PR.

Could you please, add as well `rsc` for `ReleaseServiceConfig` and `rel` for `Release`?

2023-11-14 14:36 UTC, davidmogar approved these changes

2023-11-14 14:40 UTC, merged