fix(RHTAPBUGS-859): exposes snapshot reference to the UI
redhat-appstudio/release-service pull request #318
Opened 2023-12-05 15:20 UTC by Troy876

Exposes release pipeline run snapshot information as a label

2023-12-05 15:37 UTC, davidmogar requested changes

2023-12-05 15:37 UTC, davidmogar commented on metadata/labels.go
> +	// ReleaseSnapshotLabel is the label used to specify snapshot information associated with the PipelineRun
```suggestion
	// ReleaseSnapshotLabel is the label used to specify the snapshot associated with the PipelineRun
```

2023-12-06 14:39 UTC, mmalina approved these changes

2023-12-06 14:44 UTC, theflockers approved these changes
lgtm

2023-12-06 15:27 UTC, merged