feat(HACBS-471): Add demo files for M5
redhat-appstudio/release-service pull request #34
Opened 2022-05-18 08:55 UTC by davidmogar

Adds new demo files to trigger the operator through the creations of a Release. Component and Application references have been removed.

Signed-off-by: David Moreno García <damoreno@redhat.com>

2022-05-18 12:33 UTC, johnbieren requested changes
m4 needs to be m5 all over the place (only `overlays/dev/release.yaml` even contains the string `m5`)
Why are we adding the ReleaseLink failure scenarios to the m5 demo?

2022-05-18 12:33 UTC, johnbieren commented on demos/m5/README.md
> +# Milestone 4 demo
s/4/5/

2022-05-18 12:56 UTC, davidmogar commented on demos/m5/README.md
> +$ git clone -b 0.1.0 --depth 1 https://github.com/redhat-appstudio/release-service.git
It will be 1.0.0 as we will have a breaking change (release fields change).

2022-05-18 12:58 UTC, davidmogar commented on demos/m5/base/namespaces.yaml
> +  name: demo
It should work even if you don't clean up as the resources have different names.

2022-05-18 13:01 UTC, johnbieren commented on demos/m5/base/namespaces.yaml
> +  name: demo
Look at the ReleaseLinks. They are called demo in both cases, but they target different applications. This does not appear to be true

2022-05-18 13:52 UTC, davidmogar commented on demos/m5/base/namespaces.yaml
> +  name: demo
True, I changed those names. Good catch!

2022-05-18 13:53 UTC, davidmogar commented on demos/m5/README.md
> +* a Release PipelineRun created in the `managed` namespace.
Yeah, I agree. A lot of stuff will have to be changed for M5. So far this is enough to have a way to test the current operator IMHO.

2022-05-18 13:54 UTC, davidmogar commented on demos/m5/README.md
> +### Missing matching ReleaseLink in managed workspace
Agree.

2022-05-18 19:17 UTC, johnbieren commented on demos/m5/README.md
> +* a Release PipelineRun created in the `managed` namespace.
I'd argue it makes most sense to remove either the entire README or at least the `What to expect` section from this PR then and add it once we actually have stuff to say about m5

2022-05-18 19:18 UTC, johnbieren commented on demos/m5/overlays/dev/release.yaml
> +  applicationSnapshot: m5-snapshot
I think this PR should add a snapshot (even if it is a dummy one like the params in the strategy)

2022-05-25 13:29 UTC, johnbieren requested changes

2022-05-25 13:29 UTC, johnbieren commented on demos/m5/base/application_snapshot.yaml
> +      pullSpec: pullspec1
I know these are just essentially placeholders for now, but can we add some dummy digests to these? To prevent confusion from anyone who sees these

2022-05-25 13:45 UTC, johnbieren approved these changes

2022-05-25 17:25 UTC, merged